apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: developmentchkpob
  name: developmentchkpob
  namespace: development
spec:
  containers:
  - args:
    - /bin/sleep
    - "3600"
    image: busybox
    name: developmentchkpob
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
