apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: stagingchkpob
  name: stagingchkpob
  namespace: staging
spec:
  containers:
  - args:
    - /bin/sleep
    - "3600"
    image: busybox
    name: stagingchkpob
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
