---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: stagingweb
  name: stagingweb
  namespace: staging
spec:
  initContainers:
  - name: webcontentgen
    image: busybox
    command: ['sh', '-c', "echo '==this is staging web service==' > /opt/web/index.html"]
    volumeMounts:
    - mountPath: /opt/web
      name: web
  containers:
  - image: nginx
    name: stagingweb
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: web
    resources: {}
  volumes:
  - name: web
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: stagingweb
  name: stagingweb
  namespace: staging
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: stagingweb
  type: NodePort
status:
  loadBalancer: {}
